function [ thomas_result ] = calc_Conc_distribution( physic_grid_previous, physic_grid_current, ...
                                                     physic_grid_previous_time_layer, ...
                                                     C_array, C_borders, ...
                                                     k_star_index, ...
                                                     alpha, delta, ...
                                                     eta_step, tau_step, ...
                                                     growth_rate, ReinoldsSchmitt_const, k_seg_const)


% [ a, b, c, F ] = thomas_coefficients_for_concentration( physic_grid_previous, physic_grid_current, ...
%                                                         physic_grid_previous_time_layer, ...
%                                                         C_array, C_borders, ...
%                                                         k_star_index, ...
%                                                         alpha, delta, ...
%                                                         eta_step, tau_step );
% 
% var_kappa(1) = 1/(1 - ReinoldsSchmitt_const*(1 - k_seg_const)*growth_rate* ...
%                (physic_grid_current(k_star_index + 2) - physic_grid_current(k_star_index + 1))); % remember about PG(k*+2) - PG(k*+1)
% var_kappa(2) = 1;
% var_mu = zeros(1, 2);

[ a, b, c, F ] = alternative_thomas_coefficients_for_concentration( physic_grid_current, ...
                                                                    C_array, C_borders, ...
                                                                    k_star_index, ...
                                                                    eta_step, tau_step, ...
                                                                    ReinoldsSchmitt_const);

hzkf = physic_grid_current(k_star_index + 2) - physic_grid_current(k_star_index + 1);
var_kappa(1) = 1/(1 - ReinoldsSchmitt_const*(1 - k_seg_const)*growth_rate*hzkf);
var_kappa(2) = 1;
var_mu = zeros(1, 2);

thomas_result = prog(a, b, c, F, var_kappa, var_mu);


end

