function [ a, b, c, F ] = thomas_coefficients_for_concentration( physic_grid_previous, physic_grid_current, ...
                                                                 physic_grid_previous_time_layer, ...
                                                                 C_array, C_borders, ...
                                                                 k_star_index, ...
                                                                 alpha, delta, ...
                                                                 eta_step, tau_step )

K = length(physic_grid_previous);
k_star = k_star_index;
c_offset = k_star;

all_parts_coef = 1:K;
coef_without_borders_liquid = all_parts_coef(k_star+2:end-1);

C_L_coef_simp = @(k_index) C_L_coef( k_index, k_star, ...
                                     physic_grid_previous, physic_grid_current, ...
                                     eta_step );
z_tau_simp = @(index)  z_tau( index, ...
                              physic_grid_previous, physic_grid_current, ...
                              tau_step );
psi_next = @(k_index) psi_var( k_index, physic_grid_current, eta_step );
psi_prev = @(k_index) psi_var( k_index, physic_grid_previous_time_layer, eta_step );
Conc_simp = @(C_index) Conc_var( C_index, C_array, C_borders, c_offset );

j = 1;
for i = coef_without_borders_liquid
    a(j) = alpha*C_L_coef_simp(i) - delta*z_tau_simp(i);
    b(j) = alpha*C_L_coef_simp(i+1) + delta*z_tau_simp(i+1);
    c(j) = alpha*C_L_coef_simp(i) + delta*z_tau_simp(i) + ...
           alpha*C_L_coef_simp(i+1) - delta*z_tau_simp(i+1) + psi_next(i+1/2);
    F(j) = psi_prev(i+1/2)*Conc_simp(i+1/2) + ...
           alpha*C_L_coef_simp(i+1)*(Conc_simp(i+3/2) - Conc_simp(i+1/2)) - ...
           alpha*C_L_coef_simp(i)*(Conc_simp(i+1/2) - Conc_simp(i-1/2)) + ...
           delta*z_tau_simp(i+1)*(Conc_simp(i+3/2) + Conc_simp(i+1/2)) - ...
           delta*z_tau_simp(i)*(Conc_simp(i+1/2) + Conc_simp(i-1/2));
    j = j + 1;
end


end

